apiVersion: v1
kind: Pod
spec:
  nodeSelector:
    vaimo.com/node-role: "jenkins"
  tolerations:
    - key: "vaimo.com/node-role"
      operator: "Equal"
      value: "jenkins"
      effect: "NoSchedule"
  containers:
    - name: node
      image: cypress/browsers:node-18.12.0-chrome-106
      command:
        - cat
      tty: true
      resources:
        requests:
          memory: "4Gi"
          cpu: "1"
        limits:
          memory: "8Gi"
          cpu: "2"
  restartPolicy: Never
