name: End-to-end tests

on:
  push:
  schedule:
    - cron: "0 6 * * *" # 06:00 UTC - morning run
    - cron: "0 14 * * *" # 14:00 UTC - afternoon run

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headed: false
          record: false

      - name: Notify Slack
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: cypress-test-saka-prj
          SLACK_USERNAME: Cypress Test Result
          SLACK_TITLE: Cypress test results for Saka.fi
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE_ON_FAILURE: "@Adam Krolak, please check the test results :pepebeaten:"
          SLACK_ICON: https://saka.fi/_next/image?url=%2Fassets%2Flogo%2Fsaka-logo.webp&w=96&q=75

      - name: Notify Slack
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: cypress-test-saka-prj
          SLACK_USERNAME: Cypress Test Result
          SLACK_TITLE: Cypress test results for Saka.fi
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE_ON_SUCCESS: "Everything work as expected :rocket:  :pepe-clap:"
          SLACK_ICON: https://saka.fi/_next/image?url=%2Fassets%2Flogo%2Fsaka-logo.webp&w=96&q=75
